apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/java-quarkus/base
- components/nodejs/base
- components/python-sample/base
- components/python/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
