apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: purple-mermaid-app
  name: python
  namespace: kkanova
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python
status:
  loadBalancer: {}
