apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejss
    app.kubernetes.io/part-of: purple-mermaid-app
  name: nodejss
  namespace: kkanova
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejss
status:
  loadBalancer: {}
